# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

matrix:
  include:
  - r: devel
  - r: release
    after_success:
      - Rscript -e 'covr::codecov()'

    before_cache: Rscript -e 'remotes::install_cran("pkgdown")'

    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github(run_dont_run = TRUE)'
      skip_cleanup: true
  - r: oldrel
  - r: 3.2
  - r: 3.1

# To prevent "unable to verify current time" on travis R-devel
env:
  global:
  - _R_CHECK_SYSTEM_CLOCK_=FALSE
